"""Build the combined grid + chart HTML.

Reads pre-built grid data from data/grid.json (generated by build_data_charts.py).
"""
import json
import os

BASE = os.path.dirname(__file__)
GRID_JSON = os.path.join(BASE, "data", "grid.json")

with open(GRID_JSON, "r") as f:
    grid = json.load(f)

grid_data_js = (
    f"const COINS = {json.dumps(grid['coins'])};\n"
    f"const TIMESTAMPS = {json.dumps(grid['timestamps'])};\n"
    f"const EXCHANGES_LIST = {json.dumps(grid['exchanges'])};\n"
    f"const RATES = {json.dumps(grid['rates'])};\n"
)

print(f"Grid: {len(grid['coins'])} coins x {len(grid['timestamps'])} timestamps x {len(grid['exchanges'])} exchanges")

# ── HTML template ────────────────────────────────────────────────────────────
HTML_TOP = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Funding Rate Explorer</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #f5f5f0; color: #222; font-family: monospace; font-size: 11px; padding: 0; margin: 0; }
  #grid-view { padding: 16px; }
  h2 { color: #222; font-size: 14px; margin-bottom: 4px; }
  p.sub { color: #666; font-size: 10px; margin-top: 0; margin-bottom: 10px; }
  .toolbar { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }
  .toggle-group { display: flex; border: 1px solid #bbb; border-radius: 6px; overflow: hidden; }
  .toggle-btn {
    background: #e8e8e8; color: #444; border: none; padding: 5px 14px;
    cursor: pointer; font-family: monospace; font-size: 11px; font-weight: bold;
    border-right: 1px solid #bbb; transition: background 0.15s, color 0.15s;
  }
  .toggle-btn:last-child { border-right: none; }
  .toggle-btn.active { background: #3a6ea8; color: #fff; }
  .toggle-btn:hover:not(.active) { background: #d4d4d4; }
  .mode-label { color: #666; font-size: 10px; }
  .wrap { overflow: auto; max-height: calc(100vh - 90px); }
  table { border-collapse: collapse; white-space: nowrap; }
  th {
    background: #e0e0d8; color: #333; padding: 4px 3px; text-align: center;
    border: 1px solid #ccc; position: sticky; top: 0; z-index: 2; font-size: 10px; cursor: pointer;
  }
  th.ts { position: sticky; left: 0; z-index: 3; min-width: 90px; cursor: default; }
  th:hover:not(.ts) { background: #c8d8e8; }
  td { padding: 2px 3px; text-align: right; border: 1px solid #ddd; font-size: 10px; min-width: 28px; cursor: pointer; }
  td.ts {
    background: #e8e8e4; color: #444; position: sticky; left: 0; z-index: 1;
    padding: 2px 8px; text-align: left; border-right: 2px solid #bbb; cursor: default;
  }
  tr:hover td { filter: brightness(0.93); }
  #chart-modal {
    display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%;
    background: rgba(0,0,0,0.85); z-index: 100;
  }
  #chart-modal.visible { display: flex; flex-direction: column; }
  #modal-header {
    display: flex; align-items: center; gap: 16px; padding: 12px 24px;
    background: #161b22; border-bottom: 1px solid #30363d; flex-wrap: wrap;
  }
  #modal-header label { font-size: 13px; color: #8b949e; font-family: sans-serif; }
  #modal-header select, #modal-header input {
    background: #0d1117; color: #c9d1d9; border: 1px solid #30363d;
    border-radius: 6px; padding: 6px 10px; font-size: 14px; font-family: sans-serif;
  }
  #modal-header .toggle-group { border-color: #30363d; }
  #modal-header .toggle-btn {
    background: #21262d; color: #8b949e; border-color: #30363d; font-size: 12px; padding: 5px 10px;
  }
  #modal-header .toggle-btn.active { background: #3a6ea8; color: #fff; }
  #modal-header .toggle-btn:hover:not(.active) { background: #30363d; }
  .mfield { display: flex; flex-direction: column; gap: 4px; }
  #close-btn {
    margin-left: auto; background: #da3633; color: #fff; border: none;
    border-radius: 6px; padding: 6px 16px; font-size: 14px; cursor: pointer; font-family: sans-serif;
  }
  #close-btn:hover { background: #f85149; }
  #chart { flex: 1; }
  #status { padding: 4px 24px; font-size: 12px; color: #8b949e; font-family: sans-serif; }
</style>
</head>
<body>

<div id="grid-view">
  <h2>Max Cross-Exchange Spread by Coin &mdash; 8h Windows</h2>
  <p class="sub">spread_bps = max(rate) &minus; min(rate) across exchanges &nbsp;|&nbsp; 00:00 / 08:00 / 16:00 UTC &nbsp;|&nbsp; click a column or cell to drill down</p>
  <div class="toolbar">
    <div class="toggle-group" id="exch-toggles"></div>
  </div>
  <div class="wrap">
    <table><thead id="thead"></thead><tbody id="tbody"></tbody></table>
  </div>
</div>

<div id="chart-modal">
  <div id="modal-header">
    <div class="mfield"><label>Coin</label><select id="coin"></select></div>
    <div class="mfield">
      <label>Show</label>
      <select id="rateType">
        <option value="both" selected>Implied + Settlement</option>
        <option value="settlement">Settlement Only</option>
      </select>
    </div>
    <div class="mfield">
      <label>Venues</label>
      <div class="toggle-group" id="chart-exch-toggles"></div>
    </div>
    <button id="close-btn" onclick="closeChart()">&times; Close</button>
  </div>
  <div id="chart"></div>
  <div id="status"></div>
</div>

<script>
"""

HTML_BOTTOM = r"""
let activeExchanges = new Set(EXCHANGES_LIST);

function cellStyle(val) {
  if (val === null)  return ['#f5f5f0', '#bbb'];
  if (val < 1)       return ['#f5f5f0', '#999'];
  if (val < 5)       return ['#ffe0a0', '#444'];
  if (val < 10)      return ['#f4a028', '#222'];
  return              ['#c0392b', '#fff'];
}

function computeGrid() {
  const exchs = [...activeExchanges];
  const spreads = [];
  const coinIdx = {};
  COINS.forEach((c, i) => coinIdx[c] = i);
  for (let r = 0; r < TIMESTAMPS.length; r++) {
    const row = new Array(COINS.length).fill(null);
    for (let ci = 0; ci < COINS.length; ci++) {
      const vals = [];
      for (const e of exchs) {
        const v = RATES[e][r][ci];
        if (v !== null) vals.push(v);
      }
      if (vals.length >= 2) {
        row[ci] = Math.round((Math.max(...vals) - Math.min(...vals)) * 100) / 100;
      }
    }
    spreads.push(row);
  }
  // medians
  const meds = {};
  for (let ci = 0; ci < COINS.length; ci++) {
    const vals = [];
    for (let r = 0; r < TIMESTAMPS.length; r++) {
      if (spreads[r][ci] !== null) vals.push(spreads[r][ci]);
    }
    if (vals.length) {
      vals.sort((a, b) => a - b);
      const mid = Math.floor(vals.length / 2);
      meds[COINS[ci]] = vals.length % 2 ? vals[mid] : (vals[mid - 1] + vals[mid]) / 2;
    } else {
      meds[COINS[ci]] = null;
    }
  }
  return { spreads, meds };
}

function sortedCoins(meds) {
  return [...COINS].sort((a, b) => {
    const ma = meds[a] !== null ? meds[a] : -Infinity;
    const mb = meds[b] !== null ? meds[b] : -Infinity;
    return mb - ma;
  });
}

function buildGrid() {
  const { spreads, meds } = computeGrid();
  const coinOrder = sortedCoins(meds);
  const coinIdx = {};
  COINS.forEach((c, i) => coinIdx[c] = i);

  let hdr = '<tr><th class="ts">Timestamp</th><th style="background:#d0d0c8">MAX</th>';
  for (const coin of coinOrder) {
    hdr += `<th onclick="openChart('${coin}')">${coin}</th>`;
  }
  hdr += '</tr>';

  let body = '';
  for (let r = 0; r < TIMESTAMPS.length; r++) {
    let rowMax = null;
    for (const coin of coinOrder) {
      const v = spreads[r][coinIdx[coin]];
      if (v !== null && (rowMax === null || v > rowMax)) rowMax = v;
    }
    const [maxBg, maxFg] = cellStyle(rowMax);
    const maxTxt = rowMax !== null ? Math.round(rowMax) : '';
    body += `<tr><td class="ts">${TIMESTAMPS[r]}</td>`;
    body += `<td style="background:${maxBg};color:${maxFg};font-weight:bold;border-right:2px solid #999">${maxTxt}</td>`;
    for (const coin of coinOrder) {
      const val = spreads[r][coinIdx[coin]];
      const [bg, fg] = cellStyle(val);
      const txt = val !== null ? Math.round(val) : '';
      body += `<td style="background:${bg};color:${fg}" onclick="openChart('${coin}')">${txt}</td>`;
    }
    body += '</tr>';
  }
  document.getElementById('thead').innerHTML = hdr;
  document.getElementById('tbody').innerHTML = body;
}

function initExchangeToggles() {
  const container = document.getElementById('exch-toggles');
  for (const exch of EXCHANGES_LIST) {
    const btn = document.createElement('button');
    btn.className = 'toggle-btn active';
    btn.textContent = exch;
    btn.dataset.exch = exch;
    btn.onclick = function() {
      if (activeExchanges.has(exch)) {
        activeExchanges.delete(exch);
        btn.classList.remove('active');
      } else {
        activeExchanges.add(exch);
        btn.classList.add('active');
      }
      buildGrid();
    };
    container.appendChild(btn);
  }
}

// ===== CHART =====
const DATA_BASE = 'data/';
const EXCHANGE_COLORS = {
  Binance: '#f0b90b', OKX: '#ffffff', Bybit: '#ff6600',
  Aster: '#a78bfa', Hyperliquid: '#4ade80', Lighter: '#38bdf8',
};
const EXCHANGES_ORDER = ['Binance', 'OKX', 'Bybit', 'Aster', 'Hyperliquid', 'Lighter'];

let chartManifest = {};
let coinChartData = {};
let chartActiveExchanges = new Set(EXCHANGES_ORDER);
let chartInitialized = false;

function initChartExchangeToggles() {
  const container = document.getElementById('chart-exch-toggles');
  for (const exch of EXCHANGES_ORDER) {
    const btn = document.createElement('button');
    btn.className = 'toggle-btn active';
    btn.textContent = exch;
    btn.dataset.exch = exch;
    btn.onclick = function() {
      if (chartActiveExchanges.has(exch)) {
        chartActiveExchanges.delete(exch);
        btn.classList.remove('active');
      } else {
        chartActiveExchanges.add(exch);
        btn.classList.add('active');
      }
      renderChart();
    };
    container.appendChild(btn);
  }
}

async function initChart() {
  const resp = await fetch(DATA_BASE + 'manifest.json');
  chartManifest = await resp.json();
  const coinSel = document.getElementById('coin');
  Object.keys(chartManifest).sort().forEach(c => coinSel.add(new Option(c, c)));
  coinSel.addEventListener('change', loadCoinChart);
  document.getElementById('rateType').addEventListener('change', renderChart);
  initChartExchangeToggles();
}

async function loadCoinChart() {
  const coin = document.getElementById('coin').value;
  if (!coin || !chartManifest[coin]) return;
  document.getElementById('status').textContent = 'Loading...';
  chartInitialized = false;
  const resp = await fetch(DATA_BASE + coin + '.json');
  coinChartData = await resp.json();

  renderChart();
  const totalRows = Object.values(coinChartData).reduce((s, r) => s + r.length, 0);
  document.getElementById('status').textContent =
    `${coin} — ${Object.keys(coinChartData).length} exchanges, ${totalRows.toLocaleString()} rows`;
}

function renderChart() {
  if (!Object.keys(coinChartData).length) return;
  const coin = document.getElementById('coin').value;
  const showBoth = document.getElementById('rateType').value === 'both';

  const visibleExchanges = EXCHANGES_ORDER.filter(e =>
    coinChartData[e] && chartActiveExchanges.has(e)
  );

  const traces = [];
  const spreadByTs = {};  // ts -> { exch: rate }

  for (const exch of visibleExchanges) {
    const color = EXCHANGE_COLORS[exch] || '#888';
    const rows = coinChartData[exch];

    // Detect settlement interval
    const allSettTimes = [];
    for (const [t, r, ev] of rows) { if (ev === 1) allSettTimes.push(t); }
    let interval = '';
    if (allSettTimes.length >= 2) {
      const gap = (allSettTimes[1] - allSettTimes[0]) / 3600000;
      interval = ` (${gap}h)`;
    }
    const label = exch + interval;

    const settTs = [], settRate = [];
    for (const [t, r, ev] of rows) {
      if (ev === 1) {
        if (showBoth) {
          settTs.push(new Date(t));
          settRate.push(r);
        } else {
          const h = new Date(t).getUTCHours();
          if (h === 0 || h === 8 || h === 16) {
            settTs.push(new Date(t));
            settRate.push(r);
            if (!spreadByTs[t]) spreadByTs[t] = {};
            spreadByTs[t][exch] = r;
          }
        }
      }
      if (showBoth) {
        if (!spreadByTs[t]) spreadByTs[t] = {};
        spreadByTs[t][exch] = r;
      }
    }

    if (showBoth) {
      const implTs = [], implRate = [];
      for (const [t, r, ev] of rows) { implTs.push(new Date(t)); implRate.push(r); }
      traces.push({
        x: implTs, y: implRate, type: 'scattergl', mode: 'lines',
        name: label, line: { color, width: 1 },        legendgroup: exch, xaxis: 'x', yaxis: 'y',
        hovertemplate: '%{y:.1f}<extra>' + label + '</extra>',
      });
      traces.push({
        x: settTs, y: settRate, type: 'scattergl', mode: 'markers',
        name: label + ' settle', marker: { color, size: 5, symbol: 'diamond' },
        legendgroup: exch, showlegend: false, xaxis: 'x', yaxis: 'y',
        hovertemplate: '%{y:.1f}<extra>' + label + ' settle</extra>',
      });
    } else {
      traces.push({
        x: settTs, y: settRate, type: 'scattergl', mode: 'lines+markers',
        name: label, line: { color, width: 1.5 }, marker: { color, size: 4 },
        xaxis: 'x', yaxis: 'y',
        hovertemplate: '%{y:.1f}<extra>' + label + '</extra>',
      });
    }
  }

  const spreadTs = [], spreadVal = [], spreadText = [];
  for (const t of Object.keys(spreadByTs).map(Number).sort((a, b) => a - b)) {
    const byExch = spreadByTs[t];
    const entries = Object.entries(byExch);
    if (entries.length >= 2) {
      let maxE = entries[0], minE = entries[0];
      for (const e of entries) {
        if (e[1] > maxE[1]) maxE = e;
        if (e[1] < minE[1]) minE = e;
      }
      const spread = Math.round((maxE[1] - minE[1]) * 10) / 10;
      spreadTs.push(new Date(t));
      spreadVal.push(spread);
      spreadText.push(`${spread.toFixed(1)} bps — high: ${maxE[0]} (${maxE[1].toFixed(1)}), low: ${minE[0]} (${minE[1].toFixed(1)})`);
    }
  }

  traces.push({
    x: spreadTs, y: spreadVal, type: 'scattergl', mode: 'lines',
    name: 'Max Spread', line: { color: '#f85149', width: 1.5 },
    xaxis: 'x2', yaxis: 'y2', fill: 'tozeroy', fillcolor: 'rgba(248,81,73,0.15)',
    text: spreadText, hovertemplate: '%{text}<extra></extra>',
  });

  const layout = {
    title: { text: `${coin} — Funding Rates Across Exchanges`, font: { color: '#c9d1d9', size: 16 } },
    paper_bgcolor: '#0d1117', plot_bgcolor: '#0d1117',
    grid: { rows: 2, columns: 1, subplots: [['xy'], ['x2y2']], roworder: 'top to bottom' },
    xaxis: { color: '#8b949e', gridcolor: '#21262d', domain: [0, 1] },
    yaxis: { title: 'Funding Rate (bps)', color: '#8b949e', gridcolor: '#21262d', zeroline: true, zerolinecolor: '#30363d', domain: [0.28, 1] },
    xaxis2: { color: '#8b949e', gridcolor: '#21262d', matches: 'x', domain: [0, 1] },
    yaxis2: { title: 'Max Spread (bps)', color: '#8b949e', gridcolor: '#21262d', zeroline: true, zerolinecolor: '#30363d', domain: [0, 0.22] },
    legend: { font: { color: '#c9d1d9' }, bgcolor: 'rgba(0,0,0,0)', orientation: 'h', y: 1.02, x: 0.5, xanchor: 'center' },
    margin: { t: 60, b: 30, l: 60, r: 20 },
    hovermode: 'x unified',
  };

  const chartEl = document.getElementById('chart');
  if (!chartInitialized) {
    Plotly.newPlot(chartEl, traces, layout, { responsive: true, scrollZoom: true });
    chartEl.on('plotly_legendclick', () => false);
    chartEl.on('plotly_legenddoubleclick', () => false);
    chartInitialized = true;
  } else {
    // Preserve current zoom by merging existing axis ranges
    const cur = chartEl.layout;
    if (cur.xaxis && cur.xaxis.range) layout.xaxis.range = cur.xaxis.range;
    if (cur.yaxis && cur.yaxis.range) layout.yaxis.range = cur.yaxis.range;
    if (cur.xaxis2 && cur.xaxis2.range) layout.xaxis2.range = cur.xaxis2.range;
    if (cur.yaxis2 && cur.yaxis2.range) layout.yaxis2.range = cur.yaxis2.range;
    Plotly.react(chartEl, traces, layout);
  }
}

async function openChart(coin) {
  document.getElementById('chart-modal').classList.add('visible');
  document.getElementById('coin').value = coin;
  await loadCoinChart();
}

function closeChart() {
  document.getElementById('chart-modal').classList.remove('visible');
}

document.addEventListener('keydown', e => { if (e.key === 'Escape') closeChart(); });

initExchangeToggles();
buildGrid();
initChart();
</script>
</body>
</html>
"""

with open("index.html", "w", encoding="utf-8") as f:
    f.write(HTML_TOP)
    f.write(grid_data_js)
    f.write(HTML_BOTTOM)

print("Done - wrote index.html")
